services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=explore_stats
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U explore -d explore_stats"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  stats-server:
    build:
      context: ./stats-service/stats-server
      dockerfile: Dockerfile
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_stats
      - SPRING_DATASOURCE_USERNAME=explore
      - SPRING_DATASOURCE_PASSWORD=explore
    restart: on-failure

volumes:
  stats-db-data: